### ISSUE TITLE
Galaxy installation isn't working

### ISSUE THREAD

**Issue by AssafKatz3** [fjudith/ansible-sybase#2]
Hi,
Need to change the galaxy.yaml to galaxy.yml so it will be possible to run [ansible-galaxy collection install](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-a-collection-from-a-git-repository).
Thanks

**Comment by fjudith** [comment]
Thank you @AssafKatz3.

Let me know if the issue is resolved now

**Comment by AssafKatz3** [comment]
@fjudith Working now:
`ansible-galaxy install git+https://github.com/fjudith/ansible-sybase`
Thanks
